### ISSUE TITLE
Unhandled exception from `sendBuf`

### ISSUE THREAD

**Issue by TomMD** [aisamanra/matterhorn#121] opened 2016-11-11 17:02 UTC
I have observed the following:

                    │[23:47] An unexpected error has occurred! The exception encountered was:
                    │        sendBuf: resource vanished (Broken pipe)
                    │        Please report this error at
                    │        https://github.com/aisamanra/matterhorn/issues

While running commit c1b18747b9cb2f7d625593c309a6f6ce2e11af30

**Comment by TomMD** [comment] 2016-11-11 17:03
Should we litter `HasCallStack` everywhere and emit such a call stack on exception?

**Comment by jtdaugherty** [comment] 2016-11-11 17:58
Duplicate of #116 - let's continue the discussion there!

**Closed by jtdaugherty** 2016-11-11 17:58 UTC
