### ISSUE TITLE
Remember current message in input history

### ISSUE THREAD

**Issue by dagit** [aisamanra/matterhorn#115] opened 2016-11-03 21:01 UTC
Right now if you start typing something and then press up and then down, the message you were typing is gone. I would prefer the input history to store the current message when you press up (even though it hasn't been sent). I want this because I sometimes accidentally hit the arrow keys while typing on my kinesis.

Additionally, this entry should probably be removed again from the list when you cycle back to it.

**Comment by jtdaugherty** [comment] 2016-11-03 21:04
This is a duplicate of #65.

**Closed by jtdaugherty** 2016-11-03 21:04 UTC
Labels: bug
