### ISSUE TITLE
Visual indicator for users that are offline

### ISSUE THREAD

**Issue by elliottt** [aisamanra/matterhorn#64] opened 2016-09-07 00:53 UTC
It would be nice if you could tell if someone was logged in, like the web ui.

**Comment by jtdaugherty** [comment] 2016-09-07 02:15
Duplicate of #45.

**Closed by jtdaugherty** 2016-09-07 02:15 UTC

**Comment by elliottt** [comment] 2016-09-07 03:24
Doh! I had a look through but somehow missed that one :)

**Comment by jtdaugherty** [comment] 2016-09-07 04:12
No problem. Thanks for the ticket!
